- task: AzureFileCopy@4
  inputs:
    SourcePath: 'Build.Repository.LocalPath'
    azureSubscription: 'Visual Studio Professional Subscription(51676ae8-de35-4928-9740-db593767e317)'
    Destination: 'AzureVMs'
    storage: 'spcudiag869'
    resourceGroup: 'SPCU'
    MachineNames: 'BatchVM'
    vmsAdminUserName: 'jvandae5@fordjvdev.onmicrosoft.com'
    vmsAdminPassword: 'fv6hn3eII'
    TargetPath: 'c:\temp\BatchFX'
    enableCopyPrerequisites: true